import type {
  AppSettingsDto,
  BootstrapDto,
  CategoryDto,
  DashboardSummaryDto,
  OrderDto,
  ProductDto,
  RestaurantTableDto,
  UserDto,
} from "@gastronomy/contracts";

const isoMinutesAgo = (minutes: number) =>
  new Date(Date.now() - minutes * 60_000).toISOString();

export const demoSettings: AppSettingsDto = {
  businessName: "Delta Nube · Local demo",
  currency: "ARS",
  halfAndHalfPricingMode: "HALF_PLUS_HALF",
  stockEnabled: true,
  maxConcurrentCashSessions: 1,
  allowCloseWithPendingOrders: false,
  touchProductPanelEnabled: true,
  deliverySettlementEnabled: true,
  enabledOrderStatuses: [
    "PENDING",
    "IN_PREPARATION",
    "READY",
    "OUT_FOR_DELIVERY",
    "DELIVERED",
    "CANCELLED",
  ],
  quickDelayMinutes: [15, 30, 45, 60],
  modules: {
    diningRoom: true,
    takeaway: true,
    delivery: true,
    modifiers: true,
    discounts: true,
    advancedStatuses: true,
  },
  printing: {
    terminalLabel: "Caja demo",
    kitchen: {
      profileName: "Comanda cocina",
      deviceName: "Impresora cocina (demo)",
      mode: "SYSTEM_DIRECT",
      paperWidth: "80mm",
      charsPerLine: 42,
      copies: 1,
      cutter: true,
      cutMode: "PARTIAL",
      feedLinesBeforeCut: 4,
    },
    bill: {
      profileName: "Cuenta cliente",
      deviceName: "Impresora caja (demo)",
      mode: "SYSTEM_DIRECT",
      paperWidth: "80mm",
      charsPerLine: 42,
      copies: 1,
      cutter: true,
      cutMode: "PARTIAL",
      feedLinesBeforeCut: 4,
    },
    receiptTemplate: {
      kitchenHeader: "COMANDA",
      kitchenFooter: "Preparar con atención",
      title: "Delta Nube Gastronomía",
      subtitle: "Local demo",
      footer: "Gracias por su compra",
      nonFiscalLegend: "Documento no fiscal",
      showOrderNumber: true,
      showDate: true,
      showTable: true,
      showWaiter: true,
      showCustomer: true,
      showItemQuantity: true,
      showItemUnitPrice: true,
      showItemTotal: true,
      showPaymentSummary: true,
    },
  },
};

export const demoCategories: CategoryDto[] = [
  { id: "cat-pizzas", name: "Pizzas", sortOrder: 1, active: true },
  { id: "cat-empanadas", name: "Empanadas", sortOrder: 2, active: true },
  { id: "cat-bebidas", name: "Bebidas", sortOrder: 3, active: true },
  { id: "cat-postres", name: "Postres", sortOrder: 4, active: true },
];

const prices = (salon: number, offPremise = salon) => [
  { priceListId: "price-salon", priceListCode: "SALON", amountMinor: salon },
  {
    priceListId: "price-takeaway",
    priceListCode: "TAKEAWAY",
    amountMinor: offPremise,
  },
  {
    priceListId: "price-delivery",
    priceListCode: "DELIVERY",
    amountMinor: offPremise,
  },
];

export const demoProducts: ProductDto[] = [
  {
    id: "prod-muzza",
    categoryId: "cat-pizzas",
    categoryName: "Pizzas",
    name: "Muzzarella grande",
    code: "MUZG",
    sortOrder: 1,
    active: true,
    stockMinor: 35_000,
    prices: prices(1_500_000, 1_550_000),
  },
  {
    id: "prod-napo",
    categoryId: "cat-pizzas",
    categoryName: "Pizzas",
    name: "Napolitana grande",
    code: "NAPG",
    sortOrder: 2,
    active: true,
    stockMinor: 24_000,
    prices: prices(1_800_000, 1_850_000),
  },
  {
    id: "prod-especial",
    categoryId: "cat-pizzas",
    categoryName: "Pizzas",
    name: "Especial grande",
    code: "ESPG",
    sortOrder: 3,
    active: true,
    stockMinor: 18_000,
    prices: prices(2_000_000, 2_050_000),
  },
  {
    id: "prod-emp-carne",
    categoryId: "cat-empanadas",
    categoryName: "Empanadas",
    name: "Empanada de carne",
    code: "EMPC",
    sortOrder: 1,
    active: true,
    stockMinor: 80_000,
    prices: prices(180_000),
  },
  {
    id: "prod-emp-jyq",
    categoryId: "cat-empanadas",
    categoryName: "Empanadas",
    name: "Empanada de jamón y queso",
    code: "EMPJQ",
    sortOrder: 2,
    active: true,
    stockMinor: 64_000,
    prices: prices(180_000),
  },
  {
    id: "prod-gaseosa",
    categoryId: "cat-bebidas",
    categoryName: "Bebidas",
    name: "Gaseosa 1,5 L",
    code: "GAS15",
    sortOrder: 1,
    active: true,
    stockMinor: 28_000,
    prices: prices(450_000),
  },
  {
    id: "prod-agua",
    categoryId: "cat-bebidas",
    categoryName: "Bebidas",
    name: "Agua mineral 500 ml",
    code: "AGUA",
    sortOrder: 2,
    active: true,
    stockMinor: 42_000,
    prices: prices(220_000),
  },
  {
    id: "prod-flan",
    categoryId: "cat-postres",
    categoryName: "Postres",
    name: "Flan casero",
    code: "FLAN",
    sortOrder: 1,
    active: true,
    stockMinor: 12_000,
    prices: prices(350_000),
  },
];

export const demoUsers: UserDto[] = [
  {
    id: "user-admin",
    staffNumber: 1,
    fullName: "Administrador Demo",
    roleCode: "ADMIN",
    roleName: "Administrador",
    permissions: ["*"],
    active: true,
  },
  {
    id: "user-waiter",
    staffNumber: 2,
    fullName: "Sofía Martínez",
    roleCode: "WAITER",
    roleName: "Mozo",
    permissions: ["orders.create", "orders.edit"],
    active: true,
  },
  {
    id: "user-waiter-2",
    staffNumber: 3,
    fullName: "Lucas Gómez",
    roleCode: "WAITER",
    roleName: "Mozo",
    permissions: ["orders.create", "orders.edit"],
    active: true,
  },
  {
    id: "user-driver",
    staffNumber: 4,
    fullName: "Diego López",
    roleCode: "DELIVERY_DRIVER",
    roleName: "Repartidor",
    permissions: ["deliveries.view"],
    active: true,
  },
];

function demoOrder(
  partial: Partial<OrderDto> & Pick<OrderDto, "id" | "number" | "type">,
): OrderDto {
  return {
    id: partial.id,
    number: partial.number,
    type: partial.type,
    operationalStatus: partial.operationalStatus ?? "PENDING",
    paymentStatus: partial.paymentStatus ?? "UNPAID",
    lifecycleStatus: partial.lifecycleStatus ?? "CONFIRMED",
    cashSessionCreatedId: "cash-demo",
    cashSessionPaidId: partial.cashSessionPaidId ?? null,
    tableId: partial.tableId ?? null,
    tableNumber: partial.tableNumber ?? null,
    customerId: partial.customerId ?? null,
    customerNameSnapshot: partial.customerNameSnapshot ?? null,
    customerPhoneSnapshot: partial.customerPhoneSnapshot ?? null,
    deliveryAddressSnapshot: partial.deliveryAddressSnapshot ?? null,
    deliveryAddressNotesSnapshot: partial.deliveryAddressNotesSnapshot ?? null,
    deliveryFeeMinor: partial.deliveryFeeMinor ?? 0,
    promisedAt: partial.promisedAt ?? null,
    scheduled: partial.scheduled ?? false,
    waiterUserId: partial.waiterUserId ?? null,
    waiterName: partial.waiterName ?? null,
    driverUserId: partial.driverUserId ?? null,
    driverName: partial.driverName ?? null,
    collectedByDriver: partial.collectedByDriver ?? false,
    notes: partial.notes ?? null,
    subtotalMinor: partial.subtotalMinor ?? 0,
    discountMinor: partial.discountMinor ?? 0,
    totalMinor: partial.totalMinor ?? 0,
    paidMinor: partial.paidMinor ?? 0,
    printedAt: partial.printedAt ?? null,
    printCount: partial.printCount ?? 0,
    createdAt: partial.createdAt ?? isoMinutesAgo(20),
    updatedAt: partial.updatedAt ?? isoMinutesAgo(5),
    items: partial.items ?? [],
    payments: partial.payments ?? [],
  };
}

const openTableOrder = demoOrder({
  id: "order-1001",
  number: 1001,
  type: "DINE_IN",
  tableId: "table-2",
  tableNumber: 2,
  waiterUserId: "user-waiter",
  waiterName: "Sofía Martínez",
  operationalStatus: "IN_PREPARATION",
  subtotalMinor: 1_950_000,
  totalMinor: 1_950_000,
  createdAt: isoMinutesAgo(28),
  updatedAt: isoMinutesAgo(7),
  items: [
    {
      id: "item-1001-1",
      productId: "prod-muzza",
      productNameSnapshot: "Muzzarella grande",
      quantity: 1,
      unitPriceMinorSnapshot: 1_500_000,
      discountMinorSnapshot: 0,
      notes: null,
      halves: [],
      modifiers: [],
      lineTotalMinor: 1_500_000,
    },
    {
      id: "item-1001-2",
      productId: "prod-gaseosa",
      productNameSnapshot: "Gaseosa 1,5 L",
      quantity: 1,
      unitPriceMinorSnapshot: 450_000,
      discountMinorSnapshot: 0,
      notes: null,
      halves: [],
      modifiers: [],
      lineTotalMinor: 450_000,
    },
  ],
});

const takeawayOrder = demoOrder({
  id: "order-1002",
  number: 1002,
  type: "TAKEAWAY",
  operationalStatus: "READY",
  customerNameSnapshot: "Mariana Pérez",
  customerPhoneSnapshot: "11 5555-0182",
  promisedAt: isoMinutesAgo(-5),
  subtotalMinor: 2_210_000,
  totalMinor: 2_210_000,
  createdAt: isoMinutesAgo(19),
  updatedAt: isoMinutesAgo(3),
  items: [
    {
      id: "item-1002-1",
      productId: "prod-napo",
      productNameSnapshot: "Napolitana grande",
      quantity: 1,
      unitPriceMinorSnapshot: 1_850_000,
      discountMinorSnapshot: 0,
      notes: "Sin ajo",
      halves: [],
      modifiers: [],
      lineTotalMinor: 1_850_000,
    },
    {
      id: "item-1002-2",
      productId: "prod-emp-jyq",
      productNameSnapshot: "Empanada de jamón y queso",
      quantity: 2,
      unitPriceMinorSnapshot: 180_000,
      discountMinorSnapshot: 0,
      notes: null,
      halves: [],
      modifiers: [],
      lineTotalMinor: 360_000,
    },
  ],
});

const paidDelivery = demoOrder({
  id: "order-1000",
  number: 1000,
  type: "DELIVERY",
  operationalStatus: "DELIVERED",
  paymentStatus: "PAID",
  cashSessionPaidId: "cash-demo",
  customerId: "customer-ana",
  customerNameSnapshot: "Ana Rodríguez",
  customerPhoneSnapshot: "11 4444-9080",
  deliveryAddressSnapshot: "Av. Rivadavia 3250, 4° B",
  deliveryFeeMinor: 250_000,
  driverUserId: "user-driver",
  driverName: "Diego López",
  subtotalMinor: 2_100_000,
  totalMinor: 2_350_000,
  paidMinor: 2_350_000,
  createdAt: isoMinutesAgo(95),
  updatedAt: isoMinutesAgo(52),
  printedAt: isoMinutesAgo(90),
  printCount: 1,
  items: [
    {
      id: "item-1000-1",
      productId: "prod-especial",
      productNameSnapshot: "Especial grande",
      quantity: 1,
      unitPriceMinorSnapshot: 2_100_000,
      discountMinorSnapshot: 0,
      notes: null,
      halves: [],
      modifiers: [],
      lineTotalMinor: 2_100_000,
    },
  ],
  payments: [
    {
      id: "payment-1000",
      methodCode: "CASH",
      methodName: "Efectivo",
      amountMinor: 2_350_000,
      receivedMinor: 2_500_000,
      reference: null,
      createdAt: isoMinutesAgo(54),
      refundedMinor: 0,
      refundableMinor: 2_350_000,
      status: "ACTIVE",
    },
  ],
});

export function emptyDashboard(): DashboardSummaryDto {
  return {
    orderCount: 0,
    openOrderCount: 0,
    salesTotalMinor: 0,
    averageTicketMinor: 0,
    byType: { DINE_IN: 0, TAKEAWAY: 0, DELIVERY: 0 },
    byPaymentMethod: [],
  };
}

export function createDemoBootstrap(): BootstrapDto {
  const orders = [openTableOrder, takeawayOrder, paidDelivery];
  const tables: RestaurantTableDto[] = Array.from(
    { length: 12 },
    (_, index) => {
      const number = index + 1;
      return {
        id: `table-${number}`,
        number,
        name: null,
        active: true,
        sortOrder: number,
        sectorId: number > 8 ? "sector-terrace" : "sector-main",
        layoutX: 5 + ((number - 1) % 4) * 23,
        layoutY: 9 + (Math.floor((number - 1) / 4) % 3) * 29,
        layoutWidth: number % 3 === 0 ? 20 : 16,
        layoutHeight: number % 3 === 0 ? 14 : 19,
        shape:
          number % 3 === 0
            ? "RECTANGLE"
            : number % 2 === 0
              ? "ROUND"
              : "SQUARE",
        currentOrderId: number === 2 ? openTableOrder.id : null,
        currentTotalMinor: number === 2 ? openTableOrder.totalMinor : 0,
        waiterName: number === 2 ? openTableOrder.waiterName : null,
        openedAt: number === 2 ? openTableOrder.createdAt : null,
      };
    },
  );

  return {
    settings: structuredClone(demoSettings),
    currentUser: structuredClone(demoUsers[0]!),
    cashSession: {
      id: "cash-demo",
      number: 18,
      businessDate: new Date().toISOString().slice(0, 10),
      openedAt: isoMinutesAgo(180),
      closedAt: null,
      openedByUserId: "user-admin",
      openedByName: "Administrador Demo",
      openingAmountMinor: 5_000_000,
      expectedAmountMinor: 7_350_000,
      countedAmountMinor: null,
      differenceMinor: null,
      closingFloatAmountMinor: null,
      cashRemovedAmountMinor: null,
      floatDifferenceMinor: null,
      cashSalesMinor: 2_350_000,
      cashIncomeMinor: 0,
      cashExpenseMinor: 0,
      cashWithdrawalMinor: 0,
      cashRefundMinor: 0,
      status: "OPEN",
    },
    categories: structuredClone(demoCategories),
    products: structuredClone(demoProducts),
    tableSectors: [
      { id: "sector-main", name: "Salón", sortOrder: 1 },
      { id: "sector-terrace", name: "Terraza", sortOrder: 2 },
    ],
    modifiers: [
      {
        id: "mod-extra-queso",
        groupId: "group-extras",
        groupName: "Extras",
        name: "Extra queso",
        priceMinor: 250_000,
        active: true,
      },
      {
        id: "mod-sin-aceitunas",
        groupId: "group-preparacion",
        groupName: "Preparación",
        name: "Sin aceitunas",
        priceMinor: 0,
        active: true,
      },
      {
        id: "mod-faina",
        groupId: "group-extras",
        groupName: "Extras",
        name: "Fainá",
        priceMinor: 180_000,
        active: true,
      },
    ],
    tables,
    orders: structuredClone(orders),
    users: structuredClone(demoUsers),
    deliveryLedger: [
      {
        id: "ledger-1000",
        orderId: "order-1000",
        orderNumber: 1000,
        driverUserId: "user-driver",
        driverName: "Diego López",
        restaurantAmountMinor: 2_100_000,
        deliveryFeeMinor: 250_000,
        direction: "DRIVER_OWES_BUSINESS",
        amountDueMinor: 2_100_000,
        settledAmountMinor: 0,
        status: "PENDING",
        createdAt: isoMinutesAgo(52),
        settledAt: null,
      },
    ],
    driverDeliveryActivity: [],
    paymentMethods: [
      {
        id: "payment-cash",
        code: "CASH",
        name: "Efectivo",
        affectsCash: true,
        active: true,
      },
      {
        id: "payment-debit",
        code: "DEBIT",
        name: "Débito",
        affectsCash: false,
        active: true,
      },
      {
        id: "payment-transfer",
        code: "TRANSFER",
        name: "Transferencia",
        affectsCash: false,
        active: true,
      },
      {
        id: "payment-mercadopago",
        code: "MERCADOPAGO",
        name: "Mercado Pago",
        affectsCash: false,
        active: true,
      },
    ],
    printJobs: [
      {
        id: "print-demo-failed",
        orderId: "order-1002",
        orderNumber: 1002,
        kind: "KITCHEN_ORDER",
        status: "FAILED",
        printerName: "Impresora cocina (demo)",
        copies: 1,
        attempts: 1,
        lastError: "Impresora sin conexión (simulado)",
        createdAt: isoMinutesAgo(15),
        printedAt: null,
      },
    ],
    dashboard: emptyDashboard(),
  };
}
