import { contextBridge, ipcRenderer } from "electron";
import type { DesktopApi } from "@gastronomy/contracts";

const invoke = <T>(method: keyof DesktopApi, payload?: unknown) =>
  ipcRenderer.invoke(`gastronomy:${method}`, payload) as Promise<T>;

const api: DesktopApi = {
  bootstrap: () => invoke("bootstrap"),
  ensureTable: (input) => invoke("ensureTable", input),
  openCashSession: (input) => invoke("openCashSession", input),
  registerCashMovement: (input) => invoke("registerCashMovement", input),
  closeCashSession: (input) => invoke("closeCashSession", input),
  createOrder: (input) => invoke("createOrder", input),
  updateDraftOrder: (input) => invoke("updateDraftOrder", input),
  confirmOrder: (input) => invoke("confirmOrder", input),
  discardDraftOrder: (input) => invoke("discardDraftOrder", input),
  addOrderItem: (input) => invoke("addOrderItem", input),
  addHalfAndHalfItem: (input) => invoke("addHalfAndHalfItem", input),
  removeOrderItem: (input) => invoke("removeOrderItem", input),
  addOrderItemModifier: (input) => invoke("addOrderItemModifier", input),
  removeOrderItemModifier: (input) => invoke("removeOrderItemModifier", input),
  applyOrderDiscount: (input) => invoke("applyOrderDiscount", input),
  updateOrderStatus: (input) => invoke("updateOrderStatus", input),
  assignDeliveryDriver: (input) => invoke("assignDeliveryDriver", input),
  payOrder: (input) => invoke("payOrder", input),
  refundPayment: (input) => invoke("refundPayment", input),
  completeOrder: (input) => invoke("completeOrder", input),
  cancelOrder: (input) => invoke("cancelOrder", input),
  printOrder: (input) => invoke("printOrder", input),
  retryPrint: (input) => invoke("retryPrint", input),
  searchCustomers: (query) => invoke("searchCustomers", query),
  searchCustomersPage: (input) => invoke("searchCustomersPage", input),
  getCustomerProfile: (input) => invoke("getCustomerProfile", input),
  createCustomer: (input) => invoke("createCustomer", input),
  updateCustomer: (input) => invoke("updateCustomer", input),
  setCustomerActive: (input) => invoke("setCustomerActive", input),
  mergeCustomers: (input) => invoke("mergeCustomers", input),
  createCategory: (input) => invoke("createCategory", input),
  updateCategory: (input) => invoke("updateCategory", input),
  deleteCategory: (input) => invoke("deleteCategory", input),
  createProduct: (input) => invoke("createProduct", input),
  updateProduct: (input) => invoke("updateProduct", input),
  bulkUpdateProducts: (input) => invoke("bulkUpdateProducts", input),
  createModifier: (input) => invoke("createModifier", input),
  adjustStock: (input) => invoke("adjustStock", input),
  createUser: (input) => invoke("createUser", input),
  createDriver: (input) => invoke("createDriver", input),
  updateUser: (input) => invoke("updateUser", input),
  settleDelivery: (input) => invoke("settleDelivery", input),
  reverseCashMovement: (input) => invoke("reverseCashMovement", input),
  reverseDeliverySettlement: (input) =>
    invoke("reverseDeliverySettlement", input),
  configureTables: (input) => invoke("configureTables", input),
  updateTable: (input) => invoke("updateTable", input),
  deleteTable: (input) => invoke("deleteTable", input),
  exportSalesCsv: () => invoke("exportSalesCsv"),
  getDetailedReport: (filters) => invoke("getDetailedReport", filters),
  getAuditLog: (input) => invoke("getAuditLog", input),
  createBackup: () => invoke("createBackup"),
  restoreBackup: () => invoke("restoreBackup"),
  listPrinters: () => invoke("listPrinters"),
  testPrinter: (input) => invoke("testPrinter", input),
  saveSettings: (settings) => invoke("saveSettings", settings),
  getDashboard: (businessDate) => invoke("getDashboard", businessDate),
};

contextBridge.exposeInMainWorld("gastronomy", api);
